#!/bin/bash

DIR=/var/lib/snf-network
NODES=$1
ROUTER=$2
IFACE=$3
VLAN=$4
VLANS=$5
NAME=$6


if [ $# -ne 6 ]; then
  echo "$0 <list_nodes> <router> <iface> <public_vlan> <list_of_private_vlans> <name>"
  echo "$0 'dev88 89' 'dev88' 'eth0' '101' '2990 2999' 'default'"
  exit 1
fi



cat > $DIR/nodegroups/$NAME <<EOF
ROUTER=$ROUTER
INTERFACE=$IFACE
PUBLIC_VLAN=$VLAN
PRIVATE_VLANS=$VLANS
EOF


