#!/bin/bash

MAC2EUI64=/usr/bin/mac2eui64



host=$(hostname)
domain=$(hostname -d)


if [ "$GANETI_INSTANCE_PRIMARY" = "$host.$domain" ]; then

  NETWORK=$GANETI_INSTANCE_NIC0_NETWORK
  NETWORK_TYPE=$GANETI_INSTANCE_NIC0_NETWORK_TYPE
  MODE=$GANETI_INSTANCE_NIC0_MODE
  LINK=$GANETI_INSTANCE_NIC0_LINK
  MAC=$GANETI_INSTANCE_NIC0_MAC
  SUBNET6=$GANETI_INSTANCE_NIC0_NETWORK_SUBNET6
  
  if [ "$MODE" = "routed" -a "$NETWORK_TYPE" = "public" ] ; then
      EUI64=$($MAC2EUI64 $MAC $SUBNET6 2>/dev/null)
      ip -6 neigh del proxy $EUI64 dev $PUBLIC_VLAN >/dev/null 2>&1
  fi
fi

echo done
