#!/bin/bash

DEFAULT=/etc/default/snf-network

source $DEFAULT
source $CONF
source $INFRA

HOSTNAME=$(hostname)


INTERFACES=$SHAREDDIR/interfaces/$HOSTNAME
HOSTINFRA=$SHAREDDIR/infra/$HOSTNAME

if [ -e "$HOSTINFRA" ]; then
  source $HOSTINFRA
fi

if [ -e /proc/sys/net/ipv4/conf/$PUBLIC_VLAN  -o \
#     -e /proc/sys/net/ipv4/conf/$PUBLIC_BRIDGE -o \
     -e /proc/sys/net/ipv4/conf/$MASQ_VLAN -o \
     -e /proc/sys/net/ipv4/conf/$MASQ_BRIDGE -o \
     -e /proc/sys/net/ipv4/conf/$PRIVATE_VLAN -o \
     -e /proc/sys/net/ipv4/conf/$PRIVATE_BRIDGE ]; then 
  echo Interfaces already exist! Please check: 
  echo $PUBLIC_BRIDGE for bridging TAPs with public IPs
  echo $PUBLIC_VLAN for routing TAPs with public IPs
  echo $PRIVATE_VLAN  bridged on $PRIVATE_BRIDGE for private LANs
  echo $MASQ_VLAN bridged on $MASQ_BRIDGE for private IPs that get MASQUERADED
  exit 1
fi

PUBLIC_MAC=$(ip link show $PUBLIC_INTERFACE | grep link/ether | awk '{print $2}')



cat > $INTERFACES<<EOF
#auto $PUBLIC_BRIDGE
#iface $PUBLIC_BRIDGE inet manual
#  bridge_ports $PUBLIC_INTERFACE
#  bridge_stp off
#  bridge_fd 2
#  post-up ip link set $PUBLIC_BRIDGE address $PUBLIC_MAC 

auto $PUBLIC_VLAN
iface $PUBLIC_VLAN inet manual

auto $PRIVATE_VLAN
iface $PRIVATE_VLAN inet manual

auto $PRIVATE_BRIDGE
iface $PRIVATE_BRIDGE inet manual
  bridge_ports $PRIVATE_VLAN
  bridge_stp off
  bridge_fd 2
  post-up ip link set $PRIVATE_BRIDGE address $PUBLIC_MAC 

auto $MASQ_VLAN
iface $MASQ_VLAN inet manual

auto $MASQ_BRIDGE
iface $MASQ_BRIDGE inet manual
  bridge_ports $MASQ_VLAN
  bridge_stp off
  bridge_fd 2
  post-up ip link set $MASQ_BRIDGE address $PUBLIC_MAC 
EOF


ifup -i $INTERFACES -a


echo 1 > /proc/sys/net/ipv4/conf/all/forwarding
echo 1 > /proc/sys/net/ipv4/ip_forward
