#!/bin/bash

DEFAULT=/etc/default/snf-network

source $DEFAULT
source $CONF
source $INFRA

HOSTNAME=$(hostname)


INTERFACES=$SHAREDDIR/interfaces/$HOSTNAME
HOSTINFRA=$SHAREDDIR/infra/$HOSTNAME
CLUSTERINFRA=$SHAREDDIR/infra/cluster

if [ -e "$HOSTINFRA" ]; then
  source $HOSTINFRA
fi

source $CLUSTERINFRA

if [ -n "$PUBLIC_BRIDGE" -a -e /proc/sys/net/ipv4/conf/$PUBLIC_BRIDGE ]; then 
  echo Interfaces already exist! Please check: 
  echo $PUBLIC_BRIDGE for bridging TAPs with public IPs
  exit 1
elif [ -n "$PUBLIC_VLAN" -a -e /proc/sys/net/ipv4/conf/$PUBLIC_VLAN -o \
       -n "$PRIVATE_BRIDGE" -a -e /proc/sys/net/ipv4/conf/$PRIVATE_BRIDGE -o \
       -n "$PRIVATE_VLAN" -a -e /proc/sys/net/ipv4/conf/$PRIVATE_VLAN ]; then
  echo Interfaces already exist! Please check: 
  echo $PUBLIC_BRIDGE for bridging TAPs with public IPs
  echo $PUBLIC_VLAN for routing TAPs with public IPs
  echo $PRIVATE_VLAN  bridged on $PRIVATE_BRIDGE for private LANs
  exit 1
fi



if [ -n "$PUBLIC_BRIDGE" -a -n "$PUBLIC_IFACE" ]; then
  cat > $INTERFACES<<EOF
auto $PUBLIC_BRIDGE
iface $PUBLIC_BRIDGE inet manual
  bridge_ports $PUBLIC_IFACE
  bridge_stp off
  bridge_fd 2
  post-up ip link set $PUBLIC_BRIDGE address $PUBLIC_MAC 

EOF

else
  if [ -n "$PUBLIC_VLAN" ]; then
    echo PUBLIC_VLAN=$PUBLIC_VLAN >> $HOSTINFRA
    cat >> $INTERFACES<<EOF
auto $PUBLIC_VLAN
iface $PUBLIC_VLAN inet manual

EOF
  fi

  if [ -n "$PRIVATE_VLAN" -a -n "$PRIVATE_BRIDGE" ]; then
    echo PRIVATE_VLAN=$PRIVATE_VLAN >> $HOSTINFRA
    cat >> $INTERFACES<<EOF
auto $PRIVATE_VLAN
iface $PRIVATE_VLAN inet manual

auto $PRIVATE_BRIDGE
iface $PRIVATE_BRIDGE inet manual
  bridge_ports $PRIVATE_VLAN
  bridge_stp off
  bridge_fd 2
  post-up ip link set $PRIVATE_BRIDGE address $PUBLIC_MAC 

EOF

  fi
fi

ifup -i $INTERFACES -a


echo 1 > /proc/sys/net/ipv4/conf/all/forwarding
echo 1 > /proc/sys/net/ipv4/ip_forward
