#!/bin/bash

DEFAULT=/etc/default/snf-network

source $DEFAULT
source $CONF
source $INFRA

HOSTINFRA=$STATE_DIR/infra

PUBLIC_IFACE=$(ip route | grep default | awk '{print $5}')
PUBLIC_MAC=$(ip link show $PUBLIC_IFACE | grep link/ether | awk '{print $2}')



(

cat $INFRA

echo
echo "# node's public interface" 
echo PUBLIC_IFACE=$PUBLIC_IFACE 

echo 
echo "# node's public interface MAC" 
echo PUBLIC_MAC=$PUBLIC_MAC

case $SETUP in
GRNET) 
  if [ -n "$PUBLIC_VLAN_ID" ]; then
    echo 
    echo PUBLIC_VLAN=$PUBLIC_IFACE.$PUBLIC_VLAN_ID
  fi

  if [ -n "$PRIVATE_VLAN_ID" ]; then
    echo 
    echo PRIVATE_VLAN=$PUBLIC_IFACE.$PRIVATE_VLAN_ID
    echo PRIVATE_BRIDGE=$BRIDGE_PREFIX$PRIVATE_BRIDGE_ID
  fi
esac

fi


)  > $HOSTINFRA
