#!/bin/bash

source /etc/default/snf-network
source /usr/lib/snf-network/common.sh

host=$(hostname)
domain=$(hostname -d)

FIRST=0
LAST=$((GANETI_INSTANCE_NIC_COUNT - 1))
for idx in $(seq $FIRST $LAST); do
  ip=GANETI_INSTANCE_NIC${idx}_IP
  mac=GANETI_INSTANCE_NIC${idx}_MAC
  mode=GANETI_INSTANCE_NIC${idx}_MODE
  link=GANETI_INSTANCE_NIC${idx}_LINK
  network=GANETI_INSTANCE_NIC${idx}_NETWORK_SUBNET
  subnet6=GANETI_INSTANCE_NIC${idx}_NETWORK_SUBNET6
  tags=GANETI_INSTANCE_NIC${idx}_NETWORK_TAGS
  eval IP=\$$ip
  eval MAC=\$$mac
  eval MODE=\$$mode
  eval LINK=\$$link
  eval NETWORK_SUBNET=\$$network
  eval NETWORK_SUBNET6=\$$subnet6
  eval NETWORK_TAGS=\$$tags

  for tag in $NETWORK_TAGS; do
    case $tag in
    $IP_LESS_ROUTED_TAG)
      if [ "$GANETI_OLD_PRIMARY" == "$host.$domain" ]; then
        # This runs on the source node
        # We invoke get_info here in order not to log and calculate things
        # that are not needed eventually
        get_info
        delete_neighbor_proxy
      elif [ "$GANETI_NEW_PRIMARY" == "$host.$domain" ]; then
        $SNF_NETWORK_LOG $0 "Do nothing in new primary. All done by if-up script"
      fi
    ;;
    esac
  done
done

exit 0
