#!/bin/bash

DEFAULT=/etc/default/snf-network

source $DEFAULT
source $CONF


if [ ! -e "$SHAREDDIR" ]; then
  mkdir $SHAREDDIR
  mkdir $SHAREDDIR/networks
  mkdir $SHAREDDIR/infra
  mkdir $SHAREDDIR/interfaces
  mkdir $SHAREDDIR/mappings
fi

