#!/bin/bash

DEFAULT=/etc/default/snf-network

source $DEFAULT
source $CONF


if [ ! -e "$SHAREDDIR" ]; then
  mkdir $SHAREDDIR
  mkdir $SHAREDDIR/networks
  mkdir $SHAREDDIR/infra
  mkdir $SHAREDDIR/interfaces
  mkdir $SHAREDDIR/mappings
fi

if [ -z "$(grep nfdhcpd.ferm /etc/ferm/ferm.conf)" ]; then 
  echo @include 'nfdhcpd.ferm'; >> /etc/ferm/ferm.conf
  /etc/init.d/ferm restart
fi

