#!/bin/bash

# dummy script for logging script/hook actions

# Usage: caller msg

source /etc/default/snf-network

caller=$(basename $1)

shift

hooks_info="$GANETI_HOOKS_PATH $GANETI_HOOKS_PHASE"

msg="$@"

cat >>$LOGFILE <<EOF
$(date) $hooks_info $caller $msg
EOF

exit 0
