#!/bin/bash

DEFAULT=/etc/default/snf-network

source $DEFAULT
source $CONF
source $INFRA

HOSTNAME=$(hostname)

HOSTINFRA=$SHAREDDIR/infra/$HOSTNAME
CLUSTERINFRA=$SHAREDDIR/infra/cluster

PUBLIC_IFACE=$(ip route | grep default | awk '{print $5}')
PUBLIC_MAC=$(ip link show $PUBLIC_IFACE | grep link/ether | awk '{print $2}')

echo PUBLIC_IFACE=$PUBLIC_IFACE > $HOSTINFRA
echo PUBLIC_MAC=$PUBLIC_MAC >> $HOSTINFRA

source $CLUSTERINFRA

if [ -n "$PUBLIC_VLAN_ID" ]; then
  PUBLIC_VLAN=$PUBLIC_IFACE.$PUBLIC_VLAN_ID
  echo PUBLIC_VLAN=$PUBLIC_VLAN >> $HOSTINFRA
fi

if [ -n "$PRIVATE_VLAN_ID" ]; then
  PRIVATE_VLAN=$PUBLIC_IFACE.$PRIVATE_VLAN_ID
  echo PRIVATE_VLAN=$PRIVATE_VLAN >> $HOSTINFRA
fi

