#!/bin/bash

source /etc/default/snf-network

source $CONF

INFRA=$STATE_DIR/infra

NETMASK=$(ipcalc $SUBNET | grep Netmask | awk '{print $4}')
ip addr add $GATEWAY/$NETMASK dev $BRIDGE
iptables -t nat -A POSTROUTING -s $SUBNET \! -d $SUBNET -j MASQUERADE

