#!/bin/bash

source /etc/default/snf-network

source $CONF

RT_TABLES=/etc/iproute2/rt_tables

TABLE=$LINK
VLAN=$PUBLIC_VLAN
ARP_IP=$(ipcalc $SUBNET | grep HostMax | awk '{print $2}')

ip link set $VLAN up


ID=$(wc -l < $RT_TABLES)
echo $((ID+1)) $TABLE >> $RT_TABLES

if [ -n "$SUBNET" ]; then
  ip rule add iif $VLAN table $TABLE
  ip route add $SUBNET dev $VLAN table main 
  ip route add $SUBNET dev $VLAN table $TABLE
  if [ -n "$GATEWAY" ]; then
    ip route add default via $GATEWAY dev $VLAN table $TABLE
  fi
  arptables -A OUTPUT -o $VLAN --opcode request -j mangle --mangle-ip-s $ARP_IP 
  echo 1 > /proc/sys/net/ipv4/conf/all/forwarding
  echo 1 > /proc/sys/net/ipv4/conf/$VLAN/proxy_arp
fi

if [ -n "$SUBNET6" ]; then
  ip -6 rule add iif $VLAN table $TABLE
  ip -6 route add $SUBNET6 dev $VLAN table main
  ip -6 route add $SUBNET6 dev $VLAN table $TABLE
  if [ -n "$GATEWAY6" ]; then
    ip -6 route add default via $GATEWAY6 dev $VLAN table $TABLE
  fi
  echo 1 > /proc/sys/net/ipv6/conf/all/forwarding
  echo 1 > /proc/sys/net/ipv6/conf/$VLAN/proxy_ndp
fi
