#!/bin/bash
#
# Copyright 2013-2014 GRNET S.A. All rights reserved.
#
# Redistribution and use in source and binary forms, with or
# without modification, are permitted provided that the following
# conditions are met:
#
#   1. Redistributions of source code must retain the above
#      copyright notice, this list of conditions and the following
#      disclaimer.
#
#   2. Redistributions in binary form must reproduce the above
#      copyright notice, this list of conditions and the following
#      disclaimer in the documentation and/or other materials
#      provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY GRNET S.A. ``AS IS'' AND ANY EXPRESS
# OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL GRNET S.A OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
# USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
# AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and
# documentation are those of the authors and should not be
# interpreted as representing official policies, either expressed
# or implied, of GRNET S.A.

source /etc/default/snf-network
source /usr/lib/snf-network/common.sh

function fix_proxy_ndp() {

  # We invoke get_info only if needed in order not to log
  # and calculate things that are not needed eventually
  if [ "$GANETI_OLD_PRIMARY" == "$hostname" ]; then
    # This runs on the source node
    log "Fixing proxy ndp in old primary."
    get_info
    delete_neighbor_proxy
  elif [ "$GANETI_NEW_PRIMARY" == "$hostname" ]; then
    log "Do nothing in new primary. All done by if-up script"
  elif [ "$GANETI_INSTANCE_PRIMARY" == "$hostname" ]; then
    # This runs on the primary node of instance
    log "Fixing proxy ndp in primary node."
    get_info
    delete_neighbor_proxy
  fi

}

hostname=$(hostname -f)

INSTANCE=$GANETI_INSTANCE_NAME

FIRST=0
LAST=$((GANETI_INSTANCE_NIC_COUNT - 1))
for idx in $(seq $FIRST $LAST); do
  ip=GANETI_INSTANCE_NIC${idx}_IP
  mac=GANETI_INSTANCE_NIC${idx}_MAC
  mode=GANETI_INSTANCE_NIC${idx}_MODE
  link=GANETI_INSTANCE_NIC${idx}_LINK
  network=GANETI_INSTANCE_NIC${idx}_NETWORK_SUBNET
  subnet6=GANETI_INSTANCE_NIC${idx}_NETWORK_SUBNET6
  tags=GANETI_INSTANCE_NIC${idx}_NETWORK_TAGS
  eval IP=\$$ip
  eval MAC=\$$mac
  eval MODE=\$$mode
  eval LINK=\$$link
  eval NETWORK_SUBNET=\$$network
  eval NETWORK_SUBNET6=\$$subnet6
  eval NETWORK_TAGS=\$$tags

  for tag in $NETWORK_TAGS; do
    case $tag in
    $IP_LESS_ROUTED_TAG)
      log "Fixing $INSTANCE.."
      if [ "x$GANETI_OP_CODE" = "xOP_INSTANCE_MIGRATE" ]; then
        fix_proxy_ndp
      elif [ "x$GANETI_OP_CODE" = "xOP_INSTANCE_FAILOVER" ]; then
        fix_proxy_ndp
      elif [ "x$GANETI_OP_CODE" = "xOP_INSTANCE_SHUTDOWN" ]; then
        fix_proxy_ndp
      elif [ "x$GANETI_OP_CODE" = "xOP_INSTANCE_REMOVE" ]; then
        fix_proxy_ndp
      fi

    ;;
    esac
  done
done

exit 0
