#!/bin/bash

DEFAULT=/etc/default/snf-network

source $DEFAULT
source $CONF
source $INFRA

HOSTNAME=$(hostname)


INTERFACES=$SHAREDDIR/interfaces/$HOSTNAME
HOSTINFRA=$SHAREDDIR/infra/$HOSTNAME

ifdown -i $INTERFACES -a --force

