#!/bin/bash

DEFAULT=/etc/default/snf-network

source $DEFAULT
source $CONF
source $INFRA

HOSTNAME=$(hostname)

INTERFACES=$SHAREDDIR/interfaces/$HOSTNAME

if [ -e "$INTERFACES" ]; then
  ifdown -i $INTERFACES -a --force
fi
