#!/bin/bash


dir=$(dirname "$0")
. "$dir"/vif-common.sh

# taken from older vif-common.sh
dev=$vif
dev_=${dev#vif}
domid=${dev_%.*}
devid=${dev_#*.}
domname=$(xm domname $domid)

source /etc/default/snf-network
source /usr/lib/snf-network/common.sh
source $GANETI_NIC_DIR/$domname/$devid

INTERFACE=$dev
INSTANCE=$domname

get_info

try clear_routed_setup_ipv4
try clear_routed_setup_ipv6
try clear_routed_setup_firewall
try clear_ebtables
try clear_nfdhcpd

if [ "$MODE" = "routed" ]; then
  ip link set $INTERFACE up
  success
elif [ "$MODE" = "bridged" ]; then
  ip link set $INTERFACE up
  BRIDGE=$(xenstore_read_default "$XENBUS_PATH/bridge" "$LINK")
  brctl addif $BRIDGE $INTERFACE
  success
fi

for tag in $NETWORK_TAGS; do
  case $tag in
  $IP_LESS_ROUTED_TAG)
    try routed_setup_ipv4
    try routed_setup_ipv6
    try routed_setup_firewall
    try send_garp
  ;;
  $NFDHCPD_TAG)
    try setup_nfdhcpd
  ;;
  $MAC_FILTERED_TAG)
    try init_ebtables
    try setup_ebtables
  ;;
  $MASQ_TAG)
    try setup_masq
  ;;
  esac
done
