#!/bin/sh
#

add_vlan() {
	if [ -n "`echo -n "$1" | tr -d '[0-9]'`" ]; then
		echo "Invalid vlan tag $1"
		exit 1
	fi
		
	vlan=$1
	ifce=$2

	if [ -d "/sys/class/net/vlan${vlan}/bridge" ]; then
		echo "Vlan $vlan already configured"
		exit 0
	fi

	if ( grep -q "iface vlan${vlan}$" /etc/network/interfaces ); then
		echo "Vlan $vlan configured but down, bringing up"
	else
		echo "Adding vlan $vlan to /etc/network/interfaces"
		cat >>/etc/network/interfaces <<EOF
auto vlan${vlan}
iface vlan${vlan} inet manual
	bridge_ports	${ifce}.${vlan}
	bridge_stp	off
	bridge_maxwait	0
	bridge_fd	0

EOF
	fi

	/sbin/ifup "vlan${vlan}" >/dev/null 2>&1
	exit 0
}

list_vlans() {
	for iface in /sys/class/net/vlan*; do
		if [ -d "$iface/bridge" ]; then
			vlan=`basename "$iface"`
			( grep -q "iface $vlan$" /etc/network/interfaces )
			if [ $? == 0 ]; then
				echo "${vlan##vlan}"
			else
				echo "${vlan##vlan} (unconfigured)"
			fi
		fi
	done

}

case "$1" in
	add)
	if [ x"$3" != x"" ]; then
		ifce=$3
	else
		ifce="bond0"
	fi
	add_vlan "$2" "$ifce"
	;;
	remove)
	remove_vlan "$2"
	;;
	list)
	list_vlans
	;;
	*)
	echo "Usage: vlan (add number [ifce="bond0"]|remove number|list)"
	;;
esac;

