#!/bin/bash

source /etc/default/snf-network

source $CONF


if $ENABLE_AUTO_CONF_HOOKS; then

  source $STATE_DIR/infra

  NETWORK=$GANETI_GROUP_NETWORK_NAME
  MODE=$GANETI_GROUP_NETWORK_MODE
  LINK=$GANETI_GROUP_NETWORK_LINK

  . snf-network-get-network-env


  if [ "$MODE" = "routed" -a "$TYPE" = "public-routed" ]; then

    snf-network-ipless-routing-off "$LINK" "$SUBNET" "$GATEWAY" "$SUBNET6" "$GATEWAY6"

  fi


  if [ -a $ENABLE_MASQ \
       -a -n "$GATEWAY" -a "$MODE" = "bridged" \
       -a "$TYPE" = "masq" -a "$LINK" = "$MASQ_BRIDGE" ]; then

    snf-network-masq-off "$LINK" "$SUBNET" "$GATEWAY"

  fi

fi
