#!/bin/bash

source /etc/default/snf-network

source $CONF

if $ENABLE_AUTO_CONF_HOOKS; then
  
  source $STATE_DIR/infra

  NETWORK=$GANETI_GROUP_NETWORK_NAME
  MODE=$GANETI_GROUP_NETWORK_MODE
  LINK=$GANETI_GROUP_NETWORK_LINK

  . snf-network-get-network-env


  for tag in $NETWORK_TAGS; do
    case $tag in
    ip-less-routed)
      snf-network-ipless-routing-on "$LINK" "$SUBNET" "$GATEWAY" "$SUBNET6" "$GATEWAY6"
    ;;
    masq)
      snf-network-masq-on "$LINK" "$SUBNET" "$GATEWAY"
    ;;
    esac
  done
   
fi

exit 0
