#!/bin/bash

source /etc/default/snf-network

source $CONF

if $ENABLE_AUTO_CONF_HOOKS; then
  
  INFRA=$STATE_DIR/infra

  source $INFRA

  NETWORK=$GANETI_GROUP_NETWORK_NAME
  MODE=$GANETI_GROUP_NETWORK_MODE
  LINK=$GANETI_GROUP_NETWORK_LINK

  snf-network-get-network-env


  if [ "$MODE" = "routed" -a "$TYPE" = "public" ]; then

    snf-network-ipless-routing-on

  fi


  if [ -a $ENABLE_MASQ \
       -a -n "$GATEWAY" -a "$MODE" = "bridged" -a "$TYPE" = "private" ]; then

    snf-network-masq-on

  fi

fi
