#!/bin/bash

source /etc/default/snf-network

source $CONF


NODE=$GANETI_NODE_NAME

HOSTNAME=$(hostname)

if [ "$HOSTNAME" != "$NODE" ]; then
  exit 0
fi


snf-network-build-node-infra

snf-network-configure-interfaces

