#!/bin/bash

source /etc/default/snf-network

source $CONF

if $ENABLE_AUTO_CONF_HOOKS; then

  NODE=$GANETI_NODE_NAME

  HOSTNAME=$(hostname).$(hostname -d)

  if [ "$HOSTNAME" = "$NODE" ]; then
    snf-network-build-node-infra

    snf-network-configure-interfaces
  fi

fi
