#!/bin/bash
# This script run in master-node after cluster init
# Propably should run after master failover

if $ENABLE_AUTO_CONF_HOOKS; then

  snf-network-build-node-infra

  snf-network-configure-interfaces

fi
