#!/bin/bash
# This script run in master-node after cluster init
# Propably should run after master failover

source /etc/default/snf-network

source $CONF


if $ENABLE_AUTO_CONF_HOOKS; then

  snf-network-build-node-infra

  snf-network-configure-interfaces

fi

exit 0
